/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoAcceptCard: typeof import('./components/tools/AutoAcceptCard.vue')['default']
    AutoHoverCard: typeof import('./components/tools/AutoHoverCard.vue')['default']
    AutoSwapCard: typeof import('./components/tools/AutoSwapCard.vue')['default']
    ChampionPicker: typeof import('./components/ChampionPicker.vue')['default']
    ColorPicker: typeof import('./components/ColorPicker.vue')['default']
    ColorPickerWithAlpha: typeof import('./components/ColorPickerWithAlpha.vue')['default']
    CustomTitleBar: typeof import('./components/layout/CustomTitleBar.vue')['default']
    LcuImage: typeof import('./components/LcuImage.vue')['default']
    LcuQuickActionsCard: typeof import('./components/tools/LcuQuickActionsCard.vue')['default']
    LootManagerTab: typeof import('./components/career/LootManagerTab.vue')['default']
    MatchHistoryTab: typeof import('./components/career/MatchHistoryTab.vue')['default']
    NaiveUIBridge: typeof import('./components/NaiveUIBridge.vue')['default']
    NavigationSidebar: typeof import('./components/layout/NavigationSidebar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    OpggModal: typeof import('./components/OpggModal.vue')['default']
    OpggWindow: typeof import('./components/OpggWindow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpectateCard: typeof import('./components/tools/SpectateCard.vue')['default']
    SpellPicker: typeof import('./components/SpellPicker.vue')['default']
    UpdateDialog: typeof import('./components/UpdateDialog.vue')['default']
  }
}
